//wordList created by ChatGPT
const wordList = [
    { word: "javascript", hint: "A programming language commonly used for web development" },
    { word: "elephant", hint: "A large, gray mammal with a trunk" },
    { word: "computer", hint: "An electronic device for processing data" },
    { word: "jazz", hint: "A genre of music that originated in the United States" },
    { word: "giraffe", hint: "A tall, long-necked mammal native to Africa" },
    { word: "oxygen", hint: "A chemical element essential for life" },
    { word: "galaxy", hint: "A system of millions or billions of stars" },
    { word: "umbrella", hint: "A device used for protection against rain or sun" },
    { word: "chocolate", hint: "A sweet, brown food made from roasted cacao beans" },
    { word: "keyboard", hint: "An input device for a computer" },
    { word: "telephone", hint: "A communication device used for voice calls" },
    { word: "pineapple", hint: "A tropical fruit with a spiky, tough outer rind" },
    { word: "mountain", hint: "A large landform that rises prominently above its surroundings" },
    { word: "symphony", hint: "A long musical composition for a full orchestra" },
    { word: "waterfall", hint: "A natural feature where water flows over a vertical drop or a series of drops" },
    { word: "cucumber", hint: "A green vegetable often used in salads" },
    { word: "horizon", hint: "The line where the Earth's surface and the sky appear to meet" },
    { word: "whisper", hint: "To speak or say something very softly" },
    { word: "firefly", hint: "A nocturnal insect known for its bioluminescent light" },
    { word: "carousel", hint: "A rotating machine with seats for amusement rides" },
    { word: "quasar", hint: "An extremely bright and distant celestial object" },
];